---
services:
  main:
    build: .
    ports:
      - "8080:8080"
    environment:
      # logging
      LOG_LEVEL: "info"

      # metrics
      METRICS_ENABLED: "true"
      METRICS_PORT: "8081"

      LOCAL: "true"

      PULSAR_URL: "pulsar://pulsar:6650"

      # tracing
      TRACING_ENABLED: "false"
      TRACING_SAMPLERATE: "1.0"
      TRACING_SERVICE: "versitygw-webhook-pulsar-proxy"
      TRACING_VERSION: "0.0.1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4317"

      # grpc (otlp tracing)
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: info
    depends_on:
      pulsar-init:
        condition: service_completed_successfully

  pulsar:
    image: apachepulsar/pulsar:4.0.2
    ports:
      - "6650:6650"
      - "8089:8080"
    environment:
      - PULSAR_STANDALONE_USE_ZOOKEEPER=1
    command: "bin/pulsar standalone"
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  pulsar-init:
    image: apachepulsar/pulsar:4.0.2
    command: >
      bash -c "sleep 5 && \
                exec bin/pulsar-admin --admin-url=http://pulsar:8080 \
                  namespaces create public/webhook && \
                exec bin/pulsar-admin --admin-url=http://pulsar:8080 \
                  topics create public/webhook/s3-events"
    depends_on:
      pulsar:
        condition: service_healthy

  lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"  # Grafana UI
      - "4317:4317"  # OTLP
      - "4318:4318"  # OTLPHTTP
    volumes:
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
      - ./docker/grafana/dashboards.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/grafana-dashboards.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
